ktor:
  application:
    modules:
      - com.mygamingstore.ApplicationKt.module
  deployment:
port: 8080
host: "0.0.0.0"
callTimeout: 30000

postgres:
  url: "jdbc:postgresql://localhost/default"
  user: "username"
  password: "password"

jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"